package com.flansmod.client.model;

public enum EnumAnimationType
{
	NONE, BOTTOM_CLIP, CUSTOMBOTTOM_CLIP, PISTOL_CLIP,
	CUSTOMPISTOL_CLIP, TOP_CLIP, CUSTOMTOP_CLIP, SIDE_CLIP, CUSTOMSIDE_CLIP,
	P90, CUSTOMP90, SHOTGUN, CUSTOMSHOTGUN, RIFLE,
	CUSTOMRIFLE, REVOLVER, CUSTOMREVOLVER, REVOLVER2, CUSTOMREVOLVER2,
	END_LOADED, CUSTOMEND_LOADED, RIFLE_TOP, CUSTOMRIFLE_TOP, BULLPUP,
	CUSTOMBULLPUP, ALT_PISTOL_CLIP, CUSTOMALT_PISTOL_CLIP, GENERIC, CUSTOMGENERIC,
	BACK_LOADED, CUSTOMBACK_LOADED, STRIKER, CUSTOMSTRIKER, BREAK_ACTION,
	CUSTOMBREAK_ACTION, CUSTOM
}
