package com.flansmod.client.model;

public enum EnumAnimationType
{
	NONE, BOTTOM_CLIP, PISTOL_CLIP, TOP_CLIP, SIDE_CLIP, P90, SHOTGUN, RIFLE, REVOLVER, END_LOADED, RIFLE_TOP, BULLPUP, ALT_PISTOL_CLIP, GENERIC, BACK_LOADED, STRIKER, BREAK_ACTION, CUSTOM
}
